version: '3.8'
services:
  nginx:
    build:
      context: .
      dockerfile: ../Dockerfile/nginx.Dockerfile
    image: nmp-nginx
    container_name: nmp-nginx
    ports:
      # http使用
      - "80:80"
      # 邮件反向代理使用
      - "25:25"
      - "110:110"
    volumes:
      - ../../conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../../log/nginx/:/var/log/nginx/:rw
      # http使用
      - ../../conf/nginx/http.conf:/etc/nginx/http.conf:ro
      - ../../conf/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ../../app/:/var/www/html/:rw
      # 邮件反向代理使用
      - ../../conf/nginx/r_proxy.conf:/etc/nginx/r_proxy.conf:ro
    restart: always
    command: nginx -g 'daemon off;'
    networks:
      ss_v2ray:
        aliases:
          - nginx

networks:
  ss_v2ray:
    external: true
