version: '3.3'
services:
  nginx:
    build: ./docker/nginx/
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      # - ./conf/nginx/:/etc/nginx/:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./app/:/var/www/html/:rw
      - ./log/nginx/:/var/log/nginx/:rw
    restart: always
    command: nginx -g 'daemon off;'
    networks:
      - default

networks:
  default:
  