version: '3.3'
services:
  nginx:
    build: ./Docker/Nginx/
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app/:/var/www/html/:rw
      - ./conf.d/nginx/conf.d:/etc/nginx/conf.d/:ro
      - ./conf.d/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx/:/var/log/nginx/:rw
    links:
      - php:php
    restart: always
    command: nginx -g 'daemon off;'
    networks:
      - default
  php:
    build: ./Docker/PHP/
    container_name : php
    expose:
      - "9000"
    volumes:
      - ./app/:/var/www/html/:rw
      #- ./conf.d/php/php.ini-development:/usr/local/etc/php/php.ini:ro
      - ./log/php/:/var/log/php-fpm/:rw
    links:
      - mysql:mysql
    restart: always
    command: php-fpm
    networks:
      - default
  mysql:
    build: ./Docker/MySQL/
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      # - ./conf.d/mysql/conf.d:/etc/mysql/conf.d:ro
      - ./data/mysql:/var/lib/mysql/:rw
      - ./log/mysql/:/var/log/mysql/:rw
    environment:
      MYSQL_ROOT_PASSWORD: 6677446633
      # MYSQL_DATABASE: SuiteCRM
      # MYSQL_USER: SuiteCRM
      # MYSQL_PASSWORD: SuiteCRM456
    restart: always
    command: "--character-set-server=utf8"
    networks:
      - default
networks:
  default: