version: '3.7'
services:
  nginx:
    nginx:
    extends:
      file: nginx.yml
      service: nginx
    links:
      - php:php
    networks:
      - default
  php:
    extends:
      file: php-fpm.yml
      service: php
    links:
      - mysql:mysql
    networks:
      - default
  mysql:
    extends:
      file: mysql.yml
      service: mysql
    networks:
      - default
networks:
  default:
  