version: '3.7'
services:
  nginx:
    extends:
      file: nginx.yml
      service: nginx
    links:
      - php:php
    networks:
      - default
  php:
    extends:
      file: php-fpm.yml
      service: php
    networks:
      - default
networks:
  default:
  